### ISSUE TITLE
Problem connecting S3 repository

### ISSUE THREAD

**Issue by Shelliis** [LolHens/restic-android#43]
![Screenshot_20211117-100127](https://user-images.githubusercontent.com/94470303/142183401-5c44537f-8c48-45f4-b750-7e86b4013fe0.jpg)
![Screenshot_20211117-100239](https://user-images.githubusercontent.com/94470303/142183448-48f8522d-4359-4546-8871-f46f926f5675.jpg)
:

Using APK from Release 4 with Android 11 (same with Release 3)
ACCESS_KEY and SECURITY_KEY are correct and working (for example with a RaspberryPi).
Repository does not yet exist.
Error does appears after several minutes of showing progress animation when saving the repository configuration.

Anything I can do?

**Comment by LolHens** [comment]
There seems to be an issue during the dns lookup. I have an idea on how to fix this.

**Comment by Shelliis** [comment]
Sorry to ask, but did you have an idea or no idea?
(Just to exclude that a typing error has happened)

**Comment by LolHens** [comment]
I have the following idea: generating a resolv.conf into the proot environment. Didn't get around trying it out yet though.

**Comment by LolHens** [comment]
Should be fixed in v0.2.1.

**Comment by Shelliis** [comment]
It does work now for me.
Thanks a lot!
