### ISSUE TITLE
please fix versionCode & versionName in APK

### ISSUE THREAD

**Issue by IzzySoft** [LolHens/restic-android#44]
Your APKs all seem to still use the initial default version: versionCode 1 and versionName 1.0 – while the releases page already lists 5 releases (i.e. `versionCode` should be ≥ 5) with the latest one tagged "0.2.0" (suggesting a similar `versionName`). As this is not only a cosmetical thing (Android decides based on `versionCode` whether there's an update or not), could you please bring that "into sync"? For the easiest approach, you could use `versionCode` as a "release counter" (i.e. always increase it by 1), and use the tag name as `versionName`.

Thanks!

**Comment by LolHens** [comment]
should be fixed in v0.2.1

**Comment by IzzySoft** [comment]
Thanks – confirmed! Just added it to my repo then, should [show up here](https://apt.izzysoft.de/fdroid/index/apk/de.lolhens.resticui) with the next sync tomorrow (if you wish to link there, find [some badges here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)). Due to the size I can only keep one package; I hope it doesn't grow much further :see_no_evil: Updates will be pulled automatically within 24h of your making them available – so it should be pretty easy for users to keep it updated (the F-Droid client on their devices takes care for that).

**Comment by LolHens** [comment]
The F-Droid repository is a really cool project! Thank you!

**Comment by IzzySoft** [comment]
Glad you like it! :heart_eyes: For your collection:

[![Restic@IoD](https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/de.lolhens.resticui)](https://apt.izzysoft.de/fdroid/index/apk/de.lolhens.resticui)

```
[![Restic@IoD](https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/de.lolhens.resticui)](https://apt.izzysoft.de/fdroid/index/apk/de.lolhens.resticui)
```

:smiley:
